export default function B2bChargeback() {
  return (
    <>
      <section className="service-hero">
        <div className="container">
          <h1>B2B Chargeback Policy</h1>
          <p>Risk management, liability terms, and compliance regulations for API, SDK, and White-Label Partners.</p>
        </div>
      </section>

      <section className="policy-content">
        <div className="container">
          <div className="policy-text">
            <p>This B2B Chargeback Policy governs all business-to-business collaborations, including API partners, SDK integrators, White-Label platform owners, Distributors, and Super Distributors (collectively referred to as "B2B Partners") utilizing the infrastructure of <strong>Mera Digital Pay</strong>.</p>

            <h2>1. Liability for Downstream Merchants</h2>
            <ul>
              <li>B2B Partners are solely and fully liable for all transactions, disputes, fraud claims, and chargebacks generated by their downstream retail networks, sub-merchants, and agents.</li>
              <li>Mera Digital Pay acts as an infrastructure and technology provider. Any financial losses arising from disputed transactions at the retailer level will be recovered directly from the B2B Partner's corporate wallet or settlement accounts.</li>
            </ul>

            <h2>2. Compliance and Monitoring Responsibilities</h2>
            <p>B2B Partners must ensure that their downstream merchant networks strictly follow regulatory norms, including:</p>
            <ul>
              <li>Ensuring that video KYC and physical verification of merchants are completed before account activation.</li>
              <li>Enforcing the mandatory maintenance of transaction logbooks (registers) containing customer signatures/thumb impressions at all physical retail locations.</li>
              <li>Implementing real-time fraud monitoring systems to detect abnormal transaction volumes, high card-swiping rates, or split withdrawals.</li>
            </ul>

            <h2>3. Chargeback Ratio &amp; Reserve Fund</h2>
            <ul>
              <li><strong>Dispute Threshold:</strong> The B2B Partner must maintain a monthly chargeback/dispute count of less than **0.5%** of their total transaction volume.</li>
              <li><strong>Risk Reserve:</strong> Mera Digital Pay reserves the right to establish a rolling risk-reserve fund (holding a small percentage of settlements) or place a temporary hold on API payouts if the partner's network displays high fraudulent velocity or elevated dispute rates.</li>
            </ul>

            <h2>4. Dispute Proofs &amp; SLA</h2>
            <p>When a dispute is raised by an issuing bank or NPCI, the B2B Partner must coordinate with their downstream retailer to provide signed transaction registers, customer consent logs, and receipt copies:</p>
            <ul>
              <li><strong>SLA Timeline:</strong> All requested transaction logs and physical proofs must be delivered to Mera Digital Pay within **36 hours** of notification.</li>
              <li>If the B2B Partner fails to deliver valid proof within the SLA, the dispute will be settled in favor of the customer, and the chargeback amount, along with any processing penalties, will be debited from the partner's account.</li>
            </ul>

            <h2>5. Bank Penalties &amp; Regulatory Fines</h2>
            <p>Any penalty, fine, or legal cost imposed on Mera Digital Pay by NPCI, RBI, or banking partners due to compliance failures, system abuse, or high fraud rates originating from the B2B Partner's network shall be fully indemnified by the B2B Partner. Such amounts will be deducted from any outstanding payouts or corporate wallet balances.</p>

            <h2>6. Termination of Integration</h2>
            <p>Mera Digital Pay reserves the right to immediately suspend API access, restrict transaction capabilities, or terminate the business agreement with a B2B Partner if the partner is found to be in negligence of monitoring duties, displays repeated compliance failures, or fails to clear negative wallet balances within 5 business days.</p>

            <p style={{ marginTop: '40px', fontSize: '14px', color: '#64748b' }}>Last Updated: June 12, 2026</p>
          </div>
        </div>
      </section>
    </>
  );
}
